### PR TITLE
Bump version to get the latest qgrid changes

### PR DESCRIPTION
**Pull request by TimShawver**
Also uncomments line to import tests, as explained in #1

### CODE REVIEW

**Comment by isuruf** [comment]
Please use a PR from your fork in the future..

**Comment by TimShawver** [comment]
@alen12345 sounds good. I'll merge this because I want people installing via conda to get the new fixes in this version sooner rather than later. If you can open a new PR that runs the tests that would be much appreciated.

**Comment by TimShawver** [comment]
@isuruf OK thanks for letting me know...is that a convention that's documented somewhere? I didn't see that in the conda-forge docs so I'm curious as to why that's preferred.  I'm sure there's a good reason for it, just wondering what that is so I remember to do it next time.

**Comment by isuruf** [comment]
See https://conda-forge.org/docs/recipe.html#maintainer-role 

> If you want to make a change to the recipe, send a PR to the git repository from a fork. Branches of the main repository are used for maintaining different versions only.

**Comment by TimShawver** [comment]
Thanks, I'll be sure to do that next time.

**Pull request merged**
