### PR TITLE
Moved to pip

### PR DESCRIPTION
**Pull request by alen12345**

### CODE REVIEW

**Comment by TimShawver** [comment]
Could you explain the motivation behind the change to using `pip` for installation? I've generally been copying what bqplot does for deployment/installation, since that's a widget that's maintained by core devs on the ipywidgets project.  It looks like they're using `setup.py` (see their `meta.yaml` here: https://github.com/conda-forge/bqplot-feedstock/blob/master/recipe/meta.yaml#L15) so I'm hesitant to change to something different unless there's a really good reason to.

**Comment by alen12345** [comment]
I was doing the same thing too; all the packages quantopian use setuptools, so I went with the same command. Anyhow, conda-forge is moving to pip as stated by the owner @jakirkham yesterday in my recipe for pyfolio and as pointed out by conda-forge's documentation on [pip](https://conda-forge.org/docs/recipe.html#optional-bld-bat-and-or-build-sh).

This is also a good [answer](https://stackoverflow.com/questions/8550062/how-do-setuptools-distribute-and-pip-relate-to-one-another) to understand how pip and setuptools relate to each other.

In the end, pip can handle everything setuptools can, but the opposite is not true. So in our case, we should not worry about moving to pip :)

**Comment by TimShawver** [comment]
Looks good. I think I'll need to upload a new version to pypi (and update the version/sha256 here) or else the build will not include the change where you added `__init.py__` to `qgrid/tests`.  I was planning on releasing a new version today or tomorrow anyways so I can give you the version/sha256 at that point (or I can update those after merging, let me know if you'd prefer that).

**Comment by TimShawver** [comment]
I'm going to merge as is because I've uploaded the new qgrid version to pypi and I want to try out the conda build now (so I'll update the version myself, and uncomment the `- qgrid.tests`).

**Pull request merged**
